export const USE_ONCE = 'USE_ONCE';
export const DOCKER_TIMEOUT = 'DOCKER_TIMEOUT';
export const BROWSER_SERVER_TIMEOUT = 'BROWSER_SERVER_TIMEOUT';
export const DISABLE_MESSAGES = 'DISABLE_MESSAGES';
export const DEBUG_MODE = 'DEBUG_MODE';
export const DEBUG_ENABLED = 'DEBUG_ENABLED';
