export const USE_ONCE = 'USE_ONCE';
export const DOCKER_TIMEOUT = 'DOCKER_TIMEOUT';
export const BROWSER_SERVER_TIMEOUT = 'BROWSER_SERVER_TIMEOUT';
export const DISABLE_MESSAGES = 'DISABLE_MESSAGES';
